"""
report_generator.py - Generate a PDF shop record and send it via WhatsApp.

Report structure:
  1. Header     - Visbl branding + date
  2. Shop Profile - owner name, shop, location, category, registered date
  3. Stock Snapshot - inventory items table
  4. Policy Summary - tier, premium, payout cap, status
  5. Footer      - disclaimer

Upload flow:
  generate_report_pdf()  → bytes
  upload_to_whatsapp()   → media_id
  send_document(media_id=...) - done by caller
"""

import io
import json
import logging
import os
from datetime import datetime

import requests
from dotenv import load_dotenv
from fpdf import FPDF

load_dotenv()

logger = logging.getLogger(__name__)

PHONE_NUMBER_ID = os.getenv("PHONE_NUMBER_ID")
ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN")


# ─────────────────────────────────────────────
# PDF builder
# ─────────────────────────────────────────────

_BLUE = (41, 98, 255)
_DARK = (30, 30, 30)
_GREY = (120, 120, 120)
_LIGHT = (245, 247, 250)
_WHITE = (255, 255, 255)


class VisblReport(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.add_page()
        self.set_margins(15, 15, 15)

    # ── Header band ──
    def _header_band(self, title: str):
        self.set_fill_color(*_BLUE)
        self.rect(0, 0, 210, 28, "F")
        self.set_xy(15, 8)
        self.set_text_color(*_WHITE)
        self.set_font("Helvetica", "B", 16)
        self.cell(120, 10, "Visbl", ln=0)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(200, 210, 255)
        self.set_xy(15, 18)
        self.cell(120, 6, title, ln=0)
        # date top-right
        self.set_font("Helvetica", "", 8)
        self.set_text_color(200, 210, 255)
        date_str = datetime.utcnow().strftime("%-d %b %Y")
        self.set_xy(210 - 15 - 40, 18)
        self.cell(40, 6, date_str, align="R", ln=0)
        self.set_xy(15, 32)
        self.set_text_color(*_DARK)

    # ── Section heading ──
    def _section(self, title: str):
        self.ln(4)
        self.set_fill_color(*_LIGHT)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*_BLUE)
        self.cell(0, 8, f"  {title}", border=0, fill=True, ln=1)
        self.set_text_color(*_DARK)
        self.ln(1)

    # ── Key-value row ──
    def _kv(self, key: str, value: str):
        self.set_font("Helvetica", "B", 9)
        self.cell(55, 7, key, ln=0)
        self.set_font("Helvetica", "", 9)
        self.cell(0, 7, value or "-", ln=1)

    # ── Table header ──
    def _table_header(self, cols: list, widths: list):
        self.set_fill_color(*_BLUE)
        self.set_text_color(*_WHITE)
        self.set_font("Helvetica", "B", 9)
        for label, w in zip(cols, widths):
            self.cell(w, 7, label, border=0, fill=True, align="C", ln=0)
        self.ln()
        self.set_text_color(*_DARK)

    # ── Table row ──
    def _table_row(self, values: list, widths: list, fill: bool = False):
        if fill:
            self.set_fill_color(*_LIGHT)
        self.set_font("Helvetica", "", 9)
        for val, w in zip(values, widths):
            self.cell(w, 6.5, str(val), border=0, fill=fill, ln=0)
        self.ln()

    # ── Footer (every page) ──
    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*_GREY)
        self.cell(
            0,
            5,
            "This document is generated by Visbl. "
            "It represents a self-declared shop record and does not constitute a verified insurance policy.",
            align="C",
        )


def _fmt_ghs(pesewas: int | None) -> str:
    if pesewas is None:
        return "-"
    return f"GHS {pesewas / 100:,.0f}"


def generate_report_pdf(owner: dict, declaration: dict | None, policy: dict | None) -> bytes:  # noqa: C901
    """
    Build a PDF shop record from plain dicts (not ORM objects).

    Args:
        owner:       dict with keys: name, shop_name, location, category, phone_number, created_at
        declaration: dict with keys: total_stock_value_ghs, item_breakdown_json, generated_at - or None
        policy:      dict with keys: status, premium_pesewas, payout_cap_pesewas,
                     cover_start_date, last_premium_paid_at - or None
    """
    pdf = VisblReport()

    shop_name = owner.get("shop_name") or "Your Shop"
    pdf._header_band(f"Shop Record - {shop_name}")

    # ── 1. Shop Profile ──
    pdf._section("Shop Profile")
    pdf._kv("Owner", owner.get("name") or "-")
    pdf._kv("Shop Name", shop_name)
    pdf._kv("Location", owner.get("location") or "-")
    pdf._kv("Category", owner.get("category") or "-")
    pdf._kv("Phone", owner.get("phone_number") or "-")
    created = owner.get("created_at")
    pdf._kv("Registered", created.strftime("%-d %b %Y") if created else "-")

    # ── 2. Stock Snapshot ──
    pdf._section("Stock Snapshot")

    items = []
    if declaration:
        raw_json = declaration.get("item_breakdown_json")
        if raw_json:
            try:
                items = json.loads(raw_json)
            except (json.JSONDecodeError, TypeError):
                items = []

    if items:
        total_value_ghs = declaration.get("total_stock_value_ghs", 0) or 0

        col_labels = ["Item", "Qty", "Unit Price (GHS)", "Line Value (GHS)"]
        col_w = [70, 20, 45, 45]
        pdf._table_header(col_labels, col_w)

        running_total = 0.0
        for idx, item in enumerate(items):
            name = item.get("item", "Unknown")
            qty = item.get("qty", 0)
            price = item.get("price")
            line_val = qty * price if price else None
            if line_val:
                running_total += line_val

            pdf._table_row(
                [
                    name,
                    qty,
                    f"{price:,.0f}" if price else "-",
                    f"{line_val:,.0f}" if line_val else "-",
                ],
                col_w,
                fill=(idx % 2 == 1),
            )

        # Totals row
        pdf.set_fill_color(*_LIGHT)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(col_w[0] + col_w[1] + col_w[2], 7, "Declared Total Value", fill=True, ln=0, align="R")
        pdf.set_fill_color(41, 98, 255)
        pdf.set_text_color(*_WHITE)
        display_total = total_value_ghs if total_value_ghs > 0 else running_total
        pdf.cell(col_w[3], 7, f"GHS {display_total:,.0f}", fill=True, ln=1, align="C")
        pdf.set_text_color(*_DARK)

        snap_date = declaration.get("generated_at")
        if snap_date:
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(*_GREY)
            pdf.cell(0, 6, f"  Snapshot taken on {snap_date.strftime('%-d %b %Y')}", ln=1)
            pdf.set_text_color(*_DARK)
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*_GREY)
        pdf.cell(0, 8, "  No inventory data recorded yet.", ln=1)
        pdf.set_text_color(*_DARK)

    # ── 3. Policy / Shield Summary ──
    pdf._section("Shield Summary")

    if policy:
        status = (policy.get("status") or "pending").capitalize()
        pdf._kv("Status", status)
        pdf._kv("Plan", _tier_label(policy.get("premium_pesewas")))
        pdf._kv("Monthly Premium", _fmt_ghs(policy.get("premium_pesewas")))
        pdf._kv("Payout Cap", _fmt_ghs(policy.get("payout_cap_pesewas")))
        cover_start = policy.get("cover_start_date")
        pdf._kv("Cover Start", cover_start.strftime("%-d %b %Y") if cover_start else "Pending activation")
        last_paid = policy.get("last_premium_paid_at")
        pdf._kv("Last Premium Paid", last_paid.strftime("%-d %b %Y %H:%M") if last_paid else "Not yet paid")
    else:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*_GREY)
        pdf.cell(0, 8, "  No policy found for this account.", ln=1)
        pdf.set_text_color(*_DARK)

    raw = pdf.output()
    # fpdf2 returns bytearray; ensure we always return bytes
    return bytes(raw) if not isinstance(raw, bytes) else raw


def _tier_label(premium_pesewas: int | None) -> str:
    if premium_pesewas is None:
        return "-"
    if premium_pesewas <= 6000:
        return "Starter Shield"
    if premium_pesewas <= 12000:
        return "Standard Shield"
    return "Premium Shield"


# ─────────────────────────────────────────────
# WhatsApp media upload
# ─────────────────────────────────────────────


def upload_pdf_to_whatsapp(pdf_bytes: bytes, filename: str = "Visbl_Shop_Record.pdf") -> str | None:
    """
    Upload a PDF to the WhatsApp media API.

    Returns:
        media_id string on success, None on failure.
    """
    url = f"https://graph.facebook.com/v22.0/{PHONE_NUMBER_ID}/media"
    headers = {"Authorization": f"Bearer {ACCESS_TOKEN}"}

    try:
        response = requests.post(
            url,
            headers=headers,
            files={
                "file": (filename, io.BytesIO(pdf_bytes), "application/pdf"),
                "type": (None, "application/pdf"),
                "messaging_product": (None, "whatsapp"),
            },
        )
        data = response.json()
        if response.status_code == 200:
            media_id = data.get("id")
            logger.info("pdf_upload_success | media_id=%s filename=%s", media_id, filename)
            return media_id
        else:
            error = data.get("error", {})
            logger.error(
                "pdf_upload_failed | status=%s code=%s message=%s",
                response.status_code,
                error.get("code"),
                error.get("message"),
            )
            return None
    except Exception:
        logger.exception("pdf_upload_error | filename=%s", filename)
        return None
